# Generated by Django 4.0.1 on 2022-06-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsstory_options_newsstory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
